export const RESERVATION_STATUS = {
  ALREADY_RESERVED: 'ALREADY_RESERVED',
  INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS',
  NOT_FOUND: 'NOT_FOUND',
  RESERVED: 'RESERVED',
} as const;

export type ReservationStatus = typeof RESERVATION_STATUS[keyof typeof RESERVATION_STATUS];
